### ISSUE TITLE
我看到有部分ios的支持代码，但是目前没有看到演示示例，是还没有完善吗？

### ISSUE THREAD

**Issue by Coder-Wjt** [letmeNo1/Nico#1]
我看到有部分ios的支持代码，但是目前没有看到演示示例，是还没有完善吗？

**Comment by letmeNo1** [comment]
已经实现了，就是需要先手动安装类似的WDA的IOSHierarchyDumper：https://github.com/letmeNo1/IOSHierarchyDumper，然后使用规则与安卓一致

**Comment by Coder-Wjt** [comment]
对设备有要求吗？还是通用型？

**Comment by letmeNo1** [comment]
除了系统要求ios14以上，其他没有

**Comment by Coder-Wjt** [comment]
我在启动的时候遇到这样的报错：
nico_ui -s 13045d431385a5458ab71bf03c69cb07db015c40
E:\Python\Python312\Lib\site-packages\auto_nico\console_scripts\inspector_web\nico_inspector.py:164: SyntaxWarning: invalid escape sequence '\&'
  inputValue = inputValue.replace("&", "\&").replace("\"", "")
[I 240826 16:30:25 __main__:278] Launch env: {'USE_PORT': '9766'}
[I 240826 16:30:25 _device:996] BundleID: nico.dump-hierarchyUITests.hank.xctrunner
[I 240826 16:30:25 _device:1023] ProductVersion: 15.8.3
[I 240826 16:30:25 _device:1024] UDID: 13045d431385a5458ab71bf03c69cb07db015c40
 * Serving Flask app 'auto_nico.console_scripts.inspector_web.nico_inspector'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:9320
Press CTRL+C to quit
Traceback (most recent call last):
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 125, in recv
    return self._sock.recv(bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\ssl.py", line 1233, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\ssl.py", line 1106, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 666, in mount_developer_image
    self.imagemounter.mount(image_path, signature_path)
  File "E:\Python\Python312\Lib\site-packages\tidevice\_imagemounter.py", line 185, in mount
    return self.mount_fileobj(image_reader, image_size, signature_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_imagemounter.py", line 193, in mount_fileobj
    ret = self.send_recv_packet({
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 277, in send_recv_packet
    return self.recv_packet()
           ^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 272, in recv_packet
    return self.psock.recv_packet(header_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 226, in recv_packet
    header = self.recvall(4)
             ^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 136, in recvall
    chunk = self.recv(size-len(buf))
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_safe_socket.py", line 127, in recv
    raise SocketError("socket timeout") from e
tidevice.exceptions.SocketError: socket timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Python\Python312\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "E:\Python\Python312\Lib\site-packages\tidevice\__main__.py", line 1027, in main
    actions[args.subparser](args)
  File "E:\Python\Python312\Lib\site-packages\tidevice\__main__.py", line 300, in cmd_xcuitest
    d.runwda(args.bundle_id,
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 997, in runwda
    return self.xcuitest(bundle_id, target_bundle_id=target_bundle_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 802, in _connect_testmanagerd_lockdown
    conn = self.start_service(
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "E:\Python\Python312\Lib\site-packages\tidevice\_device.py", line 673, in mount_developer_image
    raise ServiceError("ImageMountFailed")
tidevice.exceptions.ServiceError: ImageMountFailed

是我的手机型号问题吗？
iPhone 7 Plus
15.8.3

**Comment by letmeNo1** [comment]
iOS暂不支持在Inspector中点击输入的操作，只能查看元素，还有遇到问题可以加我QQ 445162647
